# ======================== Spring 基本配置 ========================
server:
  port: 7777  # 服务端口
spring:
  application:
    name: config-client  # 应用名称
  servlet:
    context-path: /  # 应用的根路径
  tomcat:
    uri-encoding: UTF-8  # URI 编码设置
    accept-count: 1000  # Tomcat 最大等待连接数
    threads:
      max: 800  # Tomcat 最大线程数
      min-spare: 100  # Tomcat 最小保留线程数
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver  # MySQL 驱动类
    url: jdbc:mysql://47.76.212.170:3306/study_cloud?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=GMT%2B8
    username: study_cloud  # 数据库用户名
    password: cw0925@Q  # 数据库密码
#    url: jdbc:mysql://127.0.0.1:3306/domain_management?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=GMT%2B8
#    username: root  # 数据库用户名
#    password: cw09250610  # 数据库密码
  profiles:
    active: dev # 指定配置文件
# ======================== 用户相关配置 ========================
user:
  password:
    maxRetryCount: 5  # 密码最大重试次数
    lockTime: 10  # 错误后锁定时间（分钟）

# ======================== Redis 配置 ========================
data:
  redis:
    host: 47.76.212.170  # Redis 服务地址
    port: 6379  # Redis 端口号

# ======================== 文件上传配置 ========================
servlet:
  multipart:
    max-file-size: 10MB  # 单个文件上传大小限制
    max-request-size: 10MB  # 请求体最大大小限制

# ======================== MyBatis 配置 ========================
mybatis:
  # 指定 Mapper 映射文件的位置
  mapper-locations: classpath:mapper/*.xml
  # 指定别名包路径，用于简化映射中的类名
  type-aliases-package: org.cw0906.cn.entities
  configuration:
    map-underscore-to-camel-case: true  # 自动将数据库下划线字段映射为 Java 驼峰命名

# ======================== 其他配置（如日志） ========================
logging:
  level:
    com.atguigu.cloud: debug  # 指定包的日志级别，调试模式
  file:
    name: logs/cloud-provider-payment8001.log  # 指定日志输出文件路径
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"  # 控制台日志输出格式
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"  # 文件日志输出格式
